# Uncomment to export files outside of this ros package path
filepath: "/mnt/e/devel/local/ws_hrecog/src/recorded_data/train"

# Name of the file
filename: "/stop.avi"

# Uncomment to timestamp the videos filename
save_multi_stream_in_sequence: true

# Name of raw image topic
topicname_image: "/hololens/RIGHT_RIGHT/image"

# frames per second for input sensor_msgs/Image stream
fps: 20

# Name of empty image topic used to stop writing to file
topicname_empty: "/hololens/stop"